---
ID: "cf2c991e-aa52-469b-a081-4501fb73c4f9"
Parent: "b9d11bdf-996e-49a3-89ba-61a7d5477705"
Template: "b9d11bdf-996e-49a3-89ba-61a7d5477705"
Path: /sitecore/templates/Feature/BasicSiteA/Custom/Rendering Parameters/RelatedBlogsList/__Standard Values
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Apps/32x32/logviewer.png
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b9ff7786-3529-403e-bc4d-dadd99647af3"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\tpanchal@horizontal.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230517T195016Z
